name: Deploy to Web Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      
      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.PORT }} ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      
      - name: Deploy with rsync
        run: |
          echo "Starting deployment to ${{ secrets.HOST }}..."
          rsync -avz -e "ssh -p ${{ secrets.PORT }}" \
            --exclude '.git*' \
            --exclude '.github' \
            --delete ./ \
            ${{ secrets.USERNAME }}@${{ secrets.HOST }}:public_html/
          echo "Deployment complete"