name: Deploy to Web Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace
      
      - name: Adding Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts 2>/dev/null
      
      - name: Deploy with rsync
        run: |
          echo "Starting deployment..."
          rsync -avz -e "ssh -p ${{ secrets.PORT }}" --delete ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:public_html/
          echo "Deployment complete"