name: Deploy to Web Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build Project
        run: npm run build
      
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" > ~/.ssh/config
          
      - name: Test SSH Connection
        run: |
          ssh -v -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} "echo 'SSH Connection Test'"
      
      - name: Deploy
        if: success()
        run: |
          echo "Starting deployment..."
          rsync -avvz -e "ssh -p ${{ secrets.PORT }}" \
            --exclude '.git*' \
            --exclude '.github' \
            --exclude 'node_modules' \
            --exclude 'src' \
            --delete \
            dist/ \
            ${{ secrets.USERNAME }}@${{ secrets.HOST }}:public_html/
          echo "Deployment complete"