name: Deploy to Web Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.PORT }} ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      
      - name: Deploy
        run: |
          echo "Starting deployment..."
          rsync -avz -e "ssh -p ${{ secrets.PORT }} -o StrictHostKeyChecking=no" \
            --exclude '.git*' \
            --exclude '.github' \
            --delete ./ \
            ${{ secrets.USERNAME }}@${{ secrets.HOST }}:public_html/
          echo "Deployment complete"